// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs-88leDsBKYozj1YvLo2qXwpzfZiW9X4',
    appId: '1:861417182416:web:ba873d58c3f94322863ad5',
    messagingSenderId: '861417182416',
    projectId: 'iiysha',
    authDomain: 'iiysha.firebaseapp.com',
    storageBucket: 'iiysha.appspot.com',
    measurementId: 'G-3JSWE07TB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqM3LD7JBJbpPrCTHFAhs50aa1NtS4DIE',
    appId: '1:861417182416:android:17a0d90bc93b61ea863ad5',
    messagingSenderId: '861417182416',
    projectId: 'iiysha',
    storageBucket: 'iiysha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBImYStDBomSmMaR4p5KjNZZlS4edaOomU',
    appId: '1:861417182416:ios:c00035eb57a4cb4e863ad5',
    messagingSenderId: '861417182416',
    projectId: 'iiysha',
    storageBucket: 'iiysha.appspot.com',
    androidClientId: '861417182416-fs2uhb2aqk3r1tl9d5e14ebrh2rhnhis.apps.googleusercontent.com',
    iosClientId: '861417182416-ns195fq7m4pr5mbgm47cbc9ms7cvmuos.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBImYStDBomSmMaR4p5KjNZZlS4edaOomU',
    appId: '1:861417182416:ios:ab6f5767dadc07eb863ad5',
    messagingSenderId: '861417182416',
    projectId: 'iiysha',
    storageBucket: 'iiysha.appspot.com',
    androidClientId: '861417182416-fs2uhb2aqk3r1tl9d5e14ebrh2rhnhis.apps.googleusercontent.com',
    iosClientId: '861417182416-ptapurp35css0api6fbs725bs08q4s45.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
